/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clipper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(531b1d75ad46f5911edaae32e5fc7d6c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <cessb/clipper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <clipper_cc_pydoc.h>

void bind_clipper_cc(py::module& m)
{

    using clipper_cc    = ::gr::cessb::clipper_cc;


    py::class_<clipper_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clipper_cc>>(m, "clipper_cc", D(clipper_cc))

        .def(py::init(&clipper_cc::make),
           py::arg("clip"),
           D(clipper_cc,make)
        )
        



        ;




}








